apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  # The secret word to be injected as an environment variable into the API service
  SECRET_WORD: "AgnosSelection2026"